### PR TITLE
Feature/default required attributes

### PR DESCRIPTION
**Pull request by titouanmathis**
This PR adds support for smart merging of attributes when using the `html_attributes()` function, allowing to define default values as well as required ones.

**component/foo.twig**
```twig
{# Inherit attribute from parent context. #}
{% set attributes = attributes|default({}) %}

{# Define default and required attribues #}
{% set options = {
  default: {
    class: 'block',
  },
  required: {
    id: 'foo'
  }
} %}

<div {{ html_attributes(attributes, options) }}>
</div>
```

**index.twig**
```twig
{% include 'components/foo.twig' with { attributes: { class: 'inline', id: 'bar', aria_hidden: true } } %}
```

**HTML Output:**
```html
<div class="block inline" id="foo" aria-hidden>
</div>
```

---

## Potential final APIs

```twig
{# As a function #}
{{ html_attributes(merge_html_attributes(attr, default, required)) }}
{{ html_attributes(merge_html_attributes(attr, { default, required })) }}
{% html_element 'p' with merge_html_attributes(attr, default, required) %}{% end_html_element %}
{% html_element 'p' with merge_html_attributes(attr, { default, required }) %}{% end_html_element %}

{# As a filter #}
{{ html_attributes(attr|merge_html_attributes(default, required)) }}
{{ html_attributes(attr|merge_html_attributes({ default, required })) }}
{% html_element 'p' with attr|merge_html_attributes(default, required) %}{% end_html_element %}
{% html_element 'p' with attr|merge_html_attributes({ default, required }) %}{% end_html_element %}

{# As params of the `html_attributes` function #}
{{ html_attributes(attr, default, required) }}
{{ html_attributes(attr, { default, required }) }}
{% html_element 'p' with attr with { default, required } %}{% end_html_element %}
```

---

**TODO**
- [ ] Define if the `class` properties should always be merged (current behaviour)
- [x] Add support for these options to the `{% html_element %}` tag

### CODE REVIEW

**Review by antoine4livre — APPROVED** [review]
Nice feature 🙂 Thank you @titouanmathis

**Comment by lusimeon** [comment]
Hi @titouanmathis, +1 for the twig filter API syntax as it's easier to read when used with `html_element`.

**Comment by notjb** [comment]
Nice addition ! 
Like @lusimeon I'm in favor of the twig Filter API syntax for its readability 👍

**Comment by titouanmathis** [comment]
The API has been implemented as a filter, thanks for your feedback @lusimeon @notjb!

I have one more question. Currently, the `class` attribute is handled differently than the others as all values are merged, i.e.:

```twig
{% set final = { class: 'foo' }|merge_html_attributes({ class: 'default' }, { class: 'required' }) %}

<div {{ html_attributes(final) }}></div>
```
```html
<div class="foo default required"></div>
```

Should we drop the `default` value to only keep the given and required attributes? Which one of the following outputs should we have:

```html
<!-- current -->
<div class="foo default required"></div>

<!-- potential implementation -->
<div class="foo required"></div>
```

Any thoughts @studiometa/core?

**Comment by perruche** [comment]
> The API has been implemented as a filter, thanks for your feedback @lusimeon @notjb!
> 
> I have one more question. Currently, the `class` attribute is handled differently than the others as all values are merged, i.e.:
> 
> ```
> {% set final = { class: 'foo' }|merge_html_attributes({ class: 'default' }, { class: 'required' }) %}
> 
> <div {{ html_attributes(final) }}></div>
> ```
> 
> ```
> <div class="foo default required"></div>
> ```
> 
> Should we drop the `default` value to only keep the given and required attributes? Which one of the following outputs should we have:
> 
> ```
> 
> <div class="foo default required"></div>
> 
> 
> <div class="foo required"></div>
> ```
> 
> Any thoughts @studiometa/core?

I think we should keep the `default` value. While a bit verbose this is allowing to have a component with immutable classes, and optionnal classes. So `defaut` should be overwritten when custom classes are set

**Comment by titouanmathis** [comment]
> I think we should keep the `default` value. While a bit verbose this is allowing to have a component with immutable classes, and optionnal classes. So `defaut` should be overwritten when custom classes are set

We are on the same page as this is what I was saying by "dropping the `default` value": if a custom value is provided, the default should not be applied. The required values will always be applied and/or merged.

I'll update my code with this logic.

**Pull request merged**
